import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/beer.min.css";
import "./globals.css"; //verificar caminho, importar as libs
import "../extension/libs/cdn/beer.min";
import "../extension/libs/cdn/material-dynamic-colors.min";
import { Settings } from "@/context/Settings";
import { Header } from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog STW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Settings>
        <Header />
        {children}
      </Settings>
    </html>
  );
}
