import type { Metadata } from "next";
import "../styles/beer.min.css";
import "./globals.css";
import "../extension/libs/cdn/beer.min";
import "../extension/libs/cdn/material-dynamic-colors.min";
import { ThemeModeProvider } from "@/context/ThemeModeContext";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog STW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeModeProvider>
      <div>
        <Header />
        {children}
        <Footer />
      </div>
    </ThemeModeProvider>
  );
}
